# Generated by Django 2.0.4 on 2018-04-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Birth_date', models.CharField(max_length=100)),
                ('Mobile_number', models.CharField(max_length=100)),
                ('friends', models.ManyToManyField(related_name='_user_friends_+', to='social_network.User')),
            ],
        ),
    ]
