# Generated by Django 2.0.4 on 2018-04-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='social_network.User'),
        ),
    ]
