# Generated by Django 2.0.4 on 2018-04-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_auto_20180428_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Mobile_number',
        ),
    ]
