# Generated by Django 2.0.4 on 2018-04-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_remove_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='Mobile_number',
            field=models.CharField(default='01012345678', max_length=100),
            preserve_default=False,
        ),
    ]
