# Generated by Django 2.0.4 on 2018-04-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_auto_20180429_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='social_network.User'),
        ),
    ]
