# Generated by Django 2.0.4 on 2018-05-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0007_auto_20180429_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Birth_date',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Mobile_number',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='username',
        ),
    ]
