# Generated by Django 2.0.4 on 2018-05-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0008_auto_20180501_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
