# Generated by Django 2.0.4 on 2018-05-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_auto_20180501_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
