# Generated by Django 2.0.4 on 2018-05-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_auto_20180504_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.CharField(max_length=10),
        ),
    ]
