# Generated by Django 2.0.4 on 2018-05-07 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_auto_20180505_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='likes',
            field=models.ManyToManyField(related_name='social_networks_mypost_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
