# Generated by Django 2.0.4 on 2018-05-07 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_mypost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
