# Generated by Django 2.0.4 on 2018-07-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_auto_20180627_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(to='social_network.Group'),
        ),
    ]
