# Generated by Django 2.0.4 on 2018-07-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0010_auto_20180704_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
